import React, { useEffect, useCallback } from 'react';
import { ArrowRight, MessageSquare } from 'lucide-react';
import { QuickResponseOption } from '../../types';
import { sounds } from '../../services/soundEffects';
import { useI18n } from '../../i18n';

interface QuickResponseStripProps {
  options: QuickResponseOption[];
  onSelectOption: (actionText: string) => void;
  agentStatus: 'idle' | 'thinking' | 'waiting_approval' | 'executing_tool';
  isLastMessageAssistant: boolean;
  disabled?: boolean;
}

export const QuickResponseStrip: React.FC<QuickResponseStripProps> = React.memo(({
  options,
  onSelectOption,
  agentStatus,
  isLastMessageAssistant,
  disabled = false,
}) => {
  const { t } = useI18n();

  const handleSelect = useCallback((actionText: string) => {
    if (disabled || agentStatus !== 'idle') return;
    sounds.playChipClick();
    onSelectOption(actionText);
  }, [disabled, agentStatus, onSelectOption]);

  // Global hotkey binding: Alt+1..4 for options, Tab for single fallback continue
  useEffect(() => {
    if (disabled || agentStatus !== 'idle') return;

    const handleKeyDown = (e: KeyboardEvent) => {
      // 1. Alt + Number (1..4)
      if (e.altKey && !e.ctrlKey && !e.metaKey) {
        const num = parseInt(e.key, 10);
        if (!isNaN(num) && num >= 1 && num <= options.length && num <= 4) {
          e.preventDefault();
          const targetOpt = options[num - 1];
          if (targetOpt) {
            handleSelect(targetOpt.action || targetOpt.prompt || targetOpt.label);
          }
        }
      }

      // 2. Tab key for fallback continuation when focus is not in an input/textarea
      if (e.key === 'Tab' && !e.altKey && !e.ctrlKey && !e.metaKey && options.length === 0 && isLastMessageAssistant) {
        const activeTag = document.activeElement?.tagName?.toLowerCase();
        if (activeTag !== 'input' && activeTag !== 'textarea') {
          e.preventDefault();
          handleSelect(t.chat.continueAction);
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [disabled, agentStatus, options, isLastMessageAssistant, handleSelect, t.chat.continueAction]);

  // Don't render during active generation or if last message is not assistant
  if (agentStatus !== 'idle' || !isLastMessageAssistant) {
    return null;
  }

  // 1. Explicit Quick Replies generated by model (capped at max 4)
  if (options.length > 0) {
    const visibleOptions = options.slice(0, 4);
    return (
      <div
        className="w-full pb-1.5 px-0.5 flex items-center gap-1.5 overflow-x-auto no-scrollbar scroll-smooth animate-fadeIn select-none"
        role="group"
        aria-label={t.chat.quickResponses}
      >
        {visibleOptions.map((opt, idx) => {
          const keyHint = `Alt+${idx + 1}`;
          const rawLabel = opt.label || opt.action;
          const displayLabel = rawLabel.length > 28 ? rawLabel.substring(0, 25) + '...' : rawLabel;
          const targetPrompt = opt.prompt || opt.action || rawLabel;

          return (
            <button
              key={opt.id || `opt_${idx}`}
              type="button"
              onClick={() => handleSelect(targetPrompt)}
              className="group shrink-0 inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-sans
                bg-[var(--theme-card-bg)] hover:bg-[var(--theme-border-subtle)] active:scale-[0.98]
                border border-[var(--theme-border)] hover:border-[var(--theme-accent)]/50
                text-[var(--theme-text)] transition-all duration-150 cursor-pointer shadow-xs whitespace-nowrap"
              title={`${targetPrompt} (${keyHint})`}
            >
              <span className="text-[var(--theme-text)] font-medium truncate max-w-[220px] sm:max-w-[280px]">
                {displayLabel}
              </span>
              <span className="text-[9px] font-mono px-1.5 py-0.5 rounded-md bg-[var(--theme-panel)] text-[var(--theme-text-muted)] border border-[var(--theme-border)] group-hover:text-[var(--theme-text)] transition-colors select-none">
                {keyHint}
              </span>
            </button>
          );
        })}
      </div>
    );
  }

  // 2. Hybrid Fallback Mode (No explicit tags emitted) -> Show smart contextual continuation chips
  return (
    <div
      className="w-full pb-1.5 px-0.5 flex items-center gap-1.5 overflow-x-auto no-scrollbar scroll-smooth animate-fadeIn select-none"
      role="group"
    >
      <button
        type="button"
        onClick={() => handleSelect(t.chat.continueAction)}
        className="group shrink-0 inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-sans
          bg-[var(--theme-card-bg)] hover:bg-[var(--theme-border-subtle)] active:scale-[0.98]
          border border-[var(--theme-border)] hover:border-[var(--theme-accent)]/50
          text-[var(--theme-text)] transition-all duration-150 cursor-pointer shadow-xs whitespace-nowrap"
        title={`${t.chat.continueAction} (Tab / Alt+1)`}
      >
        <ArrowRight size={12} className="text-[var(--theme-text-muted)] group-hover:translate-x-0.5 transition-transform" />
        <span className="font-medium">{t.chat.continueAction}</span>
        <span className="text-[9px] font-mono px-1.5 py-0.5 rounded-md bg-[var(--theme-panel)] text-[var(--theme-text-muted)] border border-[var(--theme-border)]">
          Tab
        </span>
      </button>

      <button
        type="button"
        onClick={() => handleSelect(t.chat.elaborateAction)}
        className="group shrink-0 inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-sans
          bg-[var(--theme-card-bg)]/60 hover:bg-[var(--theme-border-subtle)] active:scale-[0.98]
          border border-[var(--theme-border)] hover:border-[var(--theme-accent)]/50
          text-[var(--theme-text-muted)] hover:text-[var(--theme-text)] transition-all duration-150 cursor-pointer shadow-xs whitespace-nowrap"
        title={t.chat.elaborateAction}
      >
        <MessageSquare size={12} className="text-[var(--theme-text-muted)]" />
        <span className="font-medium">{t.chat.elaborateAction}</span>
      </button>
    </div>
  );
});

QuickResponseStrip.displayName = 'QuickResponseStrip';
