import React, { useEffect, useCallback } from 'react';
import { Sparkles, ArrowRight, MessageSquare } from 'lucide-react';
import { QuickResponseOption } from '../../types';
import { sounds } from '../../services/soundEffects';
import { useI18n } from '../../i18n';

interface QuickResponseStripProps {
  options: QuickResponseOption[];
  onSelectOption: (actionText: string) => void;
  agentStatus: 'idle' | 'thinking' | 'waiting_approval' | 'executing_tool';
  isLastMessageAssistant: boolean;
  disabled?: boolean;
}

export const QuickResponseStrip: React.FC<QuickResponseStripProps> = React.memo(({
  options,
  onSelectOption,
  agentStatus,
  isLastMessageAssistant,
  disabled = false,
}) => {
  const { t } = useI18n();

  const handleSelect = useCallback((actionText: string) => {
    if (disabled || agentStatus !== 'idle') return;
    sounds.playChipClick();
    onSelectOption(actionText);
  }, [disabled, agentStatus, onSelectOption]);

  // Global hotkey binding: Alt+1..9 for options, Tab for single fallback continue
  useEffect(() => {
    if (disabled || agentStatus !== 'idle') return;

    const handleKeyDown = (e: KeyboardEvent) => {
      // 1. Alt + Number (1..9)
      if (e.altKey && !e.ctrlKey && !e.metaKey) {
        const num = parseInt(e.key, 10);
        if (!isNaN(num) && num >= 1 && num <= options.length) {
          e.preventDefault();
          const targetOpt = options[num - 1];
          if (targetOpt) {
            handleSelect(targetOpt.action);
          }
        }
      }

      // 2. Tab key for fallback continuation when focus is not in an input/textarea
      if (e.key === 'Tab' && !e.altKey && !e.ctrlKey && !e.metaKey && options.length === 0 && isLastMessageAssistant) {
        const activeTag = document.activeElement?.tagName?.toLowerCase();
        if (activeTag !== 'input' && activeTag !== 'textarea') {
          e.preventDefault();
          handleSelect(t.chat.continueAction);
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [disabled, agentStatus, options, isLastMessageAssistant, handleSelect, t.chat.continueAction]);

  // Don't render during active generation or if last message is not assistant
  if (agentStatus !== 'idle' || !isLastMessageAssistant) {
    return null;
  }

  // 1. Explicit Quick Responses generated by model
  if (options.length > 0) {
    return (
      <div
        className="w-full pb-2 px-1 flex flex-wrap items-center gap-2 animate-in fade-in slide-in-from-bottom-2 duration-200 select-none"
        role="group"
        aria-label={t.chat.quickResponses}
      >
        <div className="flex items-center gap-1.5 text-[10px] uppercase font-mono tracking-wider text-[var(--theme-text-muted)] mr-1">
          <Sparkles className="w-3 h-3 text-[var(--theme-accent)] animate-pulse" />
          <span>{t.chat.quickResponses}</span>
        </div>

        {options.map((opt, idx) => {
          const keyHint = `Alt+${idx + 1}`;
          return (
            <button
              key={opt.id || `opt_${idx}`}
              type="button"
              onClick={() => handleSelect(opt.action)}
              className="group relative inline-flex items-center gap-2 px-3 py-1.5 rounded-xl text-xs font-mono
                bg-[var(--theme-card-bg)] hover:bg-[var(--theme-border-subtle)] active:scale-[0.98]
                border border-[var(--theme-border)] hover:border-[var(--theme-accent)]
                text-[var(--theme-text)] transition-all duration-150 cursor-pointer shadow-sm"
              title={`${opt.action} (${keyHint})`}
            >
              <span className="text-[var(--theme-text)] line-clamp-1 max-w-[220px]">
                {opt.label}
              </span>
              <span className="text-[9px] font-mono px-1.5 py-0.5 rounded bg-[var(--theme-panel)] text-[var(--theme-text-muted)] border border-[var(--theme-border)] group-hover:border-[var(--theme-accent)] group-hover:text-[var(--theme-accent)] transition-colors">
                {keyHint}
              </span>
            </button>
          );
        })}
      </div>
    );
  }

  // 2. Hybrid Fallback Mode (No explicit tags emitted) -> Show smart contextual continuation chips
  return (
    <div
      className="w-full pb-2 px-1 flex flex-wrap items-center gap-2 animate-in fade-in slide-in-from-bottom-1 duration-150 select-none"
      role="group"
    >
      <button
        type="button"
        onClick={() => handleSelect(t.chat.continueAction)}
        className="group inline-flex items-center gap-2 px-3 py-1.5 rounded-xl text-xs font-mono
          bg-[var(--theme-card-bg)] hover:bg-[var(--theme-border-subtle)] active:scale-[0.98]
          border border-[var(--theme-border)] hover:border-[var(--theme-accent)]
          text-[var(--theme-text)] transition-all duration-150 cursor-pointer shadow-sm"
        title={`${t.chat.continueAction} (Tab / Alt+1)`}
      >
        <ArrowRight className="w-3.5 h-3.5 text-[var(--theme-accent)] group-hover:translate-x-0.5 transition-transform" />
        <span>{t.chat.continueAction}</span>
        <span className="text-[9px] font-mono px-1.5 py-0.5 rounded bg-[var(--theme-panel)] text-[var(--theme-text-muted)] border border-[var(--theme-border)] group-hover:text-[var(--theme-accent)]">
          Tab
        </span>
      </button>

      <button
        type="button"
        onClick={() => handleSelect(t.chat.elaborateAction)}
        className="group inline-flex items-center gap-2 px-3 py-1.5 rounded-xl text-xs font-mono
          bg-[var(--theme-card-bg)]/60 hover:bg-[var(--theme-border-subtle)] active:scale-[0.98]
          border border-[var(--theme-border)]
          text-[var(--theme-text-muted)] hover:text-[var(--theme-text)] transition-all duration-150 cursor-pointer shadow-sm"
        title={t.chat.elaborateAction}
      >
        <MessageSquare className="w-3.5 h-3.5 text-[var(--theme-text-muted)] group-hover:text-[var(--theme-accent)]" />
        <span>{t.chat.elaborateAction}</span>
      </button>
    </div>
  );
});

QuickResponseStrip.displayName = 'QuickResponseStrip';
